name: minecraft-jsh
version: '${version}'
main: io.github.seujorgenochurras.minecraftjsh.MinecraftJsh
api-version: '1.20'

commands:
  javac:
      description: "Compiles your java book in java bytecode"
      usage: /<command>

  world:
    description: gives you power
    usage: /<command>
